[openai]
api_key = ''
chat_model = "gpt-4o-mini"
embedding_model = "text-embedding-3-small"

[pinecone]
api_key = ''
index_name = ''
index_dimension = 1536

[github]
repo_owner = ""
repo_name = ""
repo_branch = ""
directory_path = ""
repo_url = "https://github.com/x/xyz.git"
access_token = ""

[firestore]
textkey = ""

[langsmith]
tracing="true"
endpoint="https://api.smith.langchain.com"
api_key=""
project=""
chat_environment=""

[google]
ai_studio_api_key = ""